### PR TITLE
Test/500 fix keyboard test

### LINKED ISSUE #500: [UI Tests] Fix Failing Test: testRemovePhraseFromMySayingsFromKeyboard()
***Describe the bug***
The KeyboardScreenTests::testRemovePhraseFromMySayingsFromKeyboard() test is failing because we now expect the empty state instead of defaulting to "Page 1 of 1" for categories w/out phrases.

***UI Test***
Circle CI showing test failure: https://app.circleci.com/pipelines/github/willowtreeapps/vocable-ios/1405/workflows/da4dc5b0-2aec-4972-bbe1-286ff304b71f/jobs/1891

Debug and fix issue, by refactoring test to account for empty state elements instead of "Page 1 of 1" pagination elements.

### PR DESCRIPTION
**Pull request by rhsalas3**
Closes issue #500 

# Description of Work
The new empty state for categories w/out phrases has caused some of our UI automation to fail. This fixes the failing test, testRemovePhraseFromMySayingsFromKeyboard(), by refactoring the test to expect the new 'Add Phrase' button that only exists for the empty state. Previously the test was looking for the "Page 1 of 1" pagination elements.

***Notes to Test***
KeyboardScreenTests should all pass on both iPad and iPhone.

### CODE REVIEW

File: VocableUITests/Screens/MainScreen.swift [hunk 1]
```diff
@@ -80,6 +81,7 @@ class MainScreen: BaseScreen {
         } while (!selectedCell.waitForExistence(timeout: 0.33))
     }
     
+    /// Assuming there is at least one page of phrases within a category, locate the cell containg the given phrase.
```
Comment (Clstroud) [inline VocableUITests/Screens/MainScreen.swift]:
```suggestion
    /// Assuming there is at least one page of phrases within a category, locate the cell containing the given phrase.
```
😄

**Review by Clstroud — APPROVED** [review]
Straightforward and to the point 💯
