### PR TITLE
#598 - Fix Listening Mode bug 🗣️ 🐞 

### LINKED ISSUE #598: Voice Recognition not always triggering
**Describe the bug**
When navigating between categories if you navigate to the listen category very quickly the Voice recognition doesn't seem to activate.  
Listen feature seems to be working fine when saying "Hey vocable" the listening is being picked up so it may seem like its only when navigating to the category.

**To Reproduce**
Quickly toggle between the listen category and a non-listen category i.e. General.

**Expected behavior**
When navigating to the Listen category I should be able to talk to vocable and the app should pick up what I am saying.

**Actual behavior**
Sometimes the app is not picking up what I am saying.
Sometime the Listen will pick up the initial phrase but will not pick up subsequent phrases.

**Device Information**
Tested on Iphone 8 simulator as well as a physical iPad device (7th or 9th gen).

### PR DESCRIPTION
**Pull request by moyerr**
Closes #598

Listening mode would sometimes stop working if the user quickly switched between the Listening category and another category. This was caused by the fact that, when switching back, a new `ListeningResponseViewController` was initialized before the old one was deinitialized. So the `SpeechRecognitionController` was still receiving signals from the "old" insance, which were interfering with the signals from the "new" one.

This was resolved by adding an activate/deactivate mechanism to the `ListeningResponseViewController`, in which it can setup and tear down its relationship with the `SpeechRecognitionController`.

### CODE REVIEW

File: Vocable/Features/Voice/ListeningResponseViewController.swift [hunk 1]
```diff
@@ -285,6 +285,29 @@ final class ListeningResponseViewController: VocableViewController {
...
+
+        transcriptionCancellable?.cancel()
+        availabilityCancellable?.cancel()
+        permissionsCancellable?.cancel()
+        classificationCancellable?.cancel()
+
+        transcriptionCancellable = nil
+        availabilityCancellable = nil
+        permissionsCancellable = nil
+        classificationCancellable = nil
```
Comment (jsmorgan42) [inline Vocable/Features/Voice/ListeningResponseViewController.swift]: Is it necessary to also make them nil? Wouldn't just calling `cancel()` suffice?

Comment (moyerr) [reply Vocable/Features/Voice/ListeningResponseViewController.swift]: The main motivation for this was the fact that there are a few places where there are nil checks for the cancellables. So basically, I didn't want us to be in a state where they are cancelled but not nil, because then we might skip over some logic when we actually don't intend to.

**Review by jsmorgan42 — APPROVED** [review]
I like it! 💯

File: Vocable/Features/Voice/SpeechRecognitionController.swift [hunk 2]
```diff
@@ -264,6 +264,7 @@ class SpeechRecognitionController: NSObject, SFSpeechRecognitionTaskDelegate, SF
         guard isPaused else {
             return
         }
+        print("RESUME LISTENING...")
```
Comment (Clstroud) [inline Vocable/Features/Voice/SpeechRecognitionController.swift:267]: Tangential: Any thoughts on integrating a logging framework as a future ticket?

File: Vocable/Features/Root/RootViewController.swift [hunk 3]
```diff
@@ -129,6 +130,13 @@ import SwiftUI
             ![categoryCarousel, viewController].contains($0)
         }
 
+        // https://github.com/willowtreeapps/vocable-ios/issues/598
+        // Deactivate any living instances of ListeningResponseViewController
+        // so the will immediately stop attempting to interact with the SpeechRecognitionController
```
Comment (Clstroud) [inline Vocable/Features/Root/RootViewController.swift]:
```suggestion
        // so they will immediately stop attempting to interact with the SpeechRecognitionController
```

File: Vocable/Features/Voice/SpeechRecognitionController.swift (hunk 2 above)
Comment (moyerr) [reply Vocable/Features/Voice/SpeechRecognitionController.swift:267]: @Clstroud I've thought about it many times! I can create a ticket for the ol' backlog

File: Vocable/Features/Voice/ListeningResponseViewController.swift [hunk 4]
```diff
@@ -285,6 +285,29 @@ final class ListeningResponseViewController: VocableViewController {
...
+    /// Activates this instance with a Speech Recognizer
+    ///
+    /// - Parameter speechRecognizer: The `SpeechRecognitionController` for transcriptions
+    func activate(withSpeechRecognizer speechRecognizer: SpeechRecognitionController) {
+        speechRecognizerController = speechRecognizer
+    }
+
+    /// Deactivates this instance by removing the speech recognizer and cancelling
+    /// any active subscriptions to the speech recognizer.
+    func deactivate() {
```
Comment (Clstroud) [inline Vocable/Features/Voice/ListeningResponseViewController.swift]: Not arguing this strongly, but at the call site I interpreted this as doing something more than it actually is. "Activate" struck me as "start doing audio stuff." which we are leaving to the discretion of the child view controller.

Makes me wonder if having `deactivate` get called from the `didSet` of the `speechRecognitionController` might be preferable?

File: Vocable/Features/Root/RootViewController.swift [hunk 5]
```diff
@@ -158,9 +166,15 @@ import SwiftUI
...
         func finalize(_ didFinish: Bool) {
             for inactiveViewController in childrenToDisposeOf {
-                inactiveViewController.removeFromParent()
+                guard inactiveViewController.parent != nil else {
+                    continue
+                }
+
+                inactiveViewController.willMove(toParent: nil)
                 inactiveViewController.view.removeFromSuperview()
+                inactiveViewController.removeFromParent()
```
Comment (Clstroud) [inline Vocable/Features/Root/RootViewController.swift:171]: >If you are implementing your own container view controller, it must call the willMove(toParent:) method of the child view controller before calling the [removeFromParent()](https://developer.apple.com/documentation/uikit/uiviewcontroller/1621425-removefromparent) method, passing in a parent value of nil.

lol. No clue who wrote this 👀  Good catch.

**Review by Clstroud — APPROVED** [review]
Couple of thoughts, but looks good! 💯

**Review by Clstroud — APPROVED** [review]
Nice and concise 💯

**Comment by CananArikan** [comment]
Test verified.
iPad Pro - Test Device - iOS 15.3.1
iPhone 11 - Simulator - iOS 15.4
