### PR TITLE
#695 | Output Text After Speech Services Unavailable

### LINKED ISSUE #695: [Listen] Old speech copy in output label when Speech services unavailable
### Describe the bug
If Listen has been in use when Siri & Dictation are disabled, the output label should not persist any questions or answers from when it was last used.

#### Pre-requisites
Speech and microphone access have been granted for Listen.
At least one or both of the Siri and Keyboard dictation system options are enabled.

#### Steps
1. On the Listen category, speak a question. 
   > As expected, the question appears in the output label. 
2. Go to system settings and disable Siri & Dictation in Screen Time. 
3. Foreground the app. The Listen category is displayed.
   > The speech services unavailable message appears. 

**Expected behavior**
 The output label is blank

**Actual behavior**
The output label shows the last question/answer

### Screenshots
Screenshot 2022-06-03 at 11 24 04 AM

### Device Information
iOS 15.0.2
iPhone 12 Max Pro
TestFlight build 2835

### PR DESCRIPTION
**Pull request by jsmorgan42**
closes #695

# Description of Work
The output text at the top of the screen will now reset to the default "Select something below to speak" when navigating back to the app after disabling Dictation or Siri.

---

### CODE REVIEW

**Comment by rowildcard** [comment]
Test verified.
iPhone 12 Pro Max, iOS 15.0.2

File: Vocable/Features/Root/RootViewController.swift [hunk 1]
```diff
@@ -291,4 +291,8 @@ import SwiftUI
         updateOutputLabelText(text, isDictated: (text != nil))
     }
 
+    func shouldResetOutputText() {
+        updateOutputLabelText(nil, isDictated: false)
+    }
```
Comment (Clstroud) [inline Vocable/Features/Root/RootViewController.swift]: I think I would probably expect this function signature to return a `Bool`? Might feel better if you drop the "should"?

**Review by Clstroud — APPROVED** [review]
One comment, but LGTM 💯
