### PR TITLE
#644 | Start speech recognition in "Hot Word" mode when enabled from Settings

### LINKED ISSUE #644: `Hey Vocable` shortcut is not navigating to the listening mode screen right after enabling listening mode
**Description**
`Hey Vocable` shortcut is not navigating to the listening mode screen right after enabling listening mode. But, when we manually navigate to the Listen category at the main screen, after app starts to listen, then `Hey vocable` shortcut works as expected. 

Update: Also, when you close and re-open the app after enabling listening mode the `Hey Vocable` shortcut does not work until you manually navigate to the Listen category.

**Steps To Reproduce**

1. Restart the app
2. Go to the Settings
3. From Listening Mode, grant accesses 
4. Say the `Hey vocable` shortcut at the Settings Screen or Main Screen

**Expected behavior**
`Hey Vocable` shortcut is navigating to the listening mode screen.
After closing and restarting the app, `Hey Vocable` shortcut will navigate use to the listening mode screen

**Actual behavior**
`Hey Vocable` shortcut is not navigating to the listening mode screen.

**Device Information**
iPad Pro - Test Device - iOS 15.3.1

**Build**
1.4.1-1

**Screenshots**

https://user-images.githubusercontent.com/100222793/167493073-01188ecf-185c-4a2e-a2a1-87cf13c744b7.mov

### PR DESCRIPTION
**Pull request by moyerr**
Closes #644

# Description of Work

This PR fixes an issue where the `SpeechRecognitionController` would always fire up in "transcription" mode when the user first granted permissions. This is the desired mode when we grant permissions from the Listen category on the Home screen, however this is not what we want when permissions are granted from the Settings screen. Instead, the "hot word" mode should be activated, so the app can properly handle actions after it recognizes the Hot Word.

### CODE REVIEW

File: Vocable/Features/Voice/AudioPermissionPromptController.swift [hunk 1]
```diff
@@ -51,9 +54,11 @@ final class AudioPermissionPromptController {
...
             })
         case .notDetermined: // Need to present alert
-            return .init(state: .speechPermissionUndetermined, action: {
-                SpeechRecognitionController.shared.startTranscribing(requestPermission: .speech)
-            })
+            return .init(state: .speechPermissionUndetermined) { [desiredListeningMode] in
+                SpeechRecognitionController.shared.startListening(
+                    mode: desiredListeningMode,
+                    requestablePermission: .speech)
+            }
```
Comment (jsmorgan42) [inline Vocable/Features/Voice/AudioPermissionPromptController.swift:61]: I'm confused where this `desiredListeningMode` variable is coming from, isn't the action not just a basic closure with no parameters to pass in?

File: Vocable/Features/Voice/AudioPermissionPromptController.swift [hunk 2]
```diff
@@ -21,8 +21,11 @@ final class AudioPermissionPromptController {
     @Published private(set) var state: AudioPermissionEmptyState? = .none
 
     private var cancellables = Set<AnyCancellable>()
+    private let desiredListeningMode: SpeechRecognitionController.ListeningMode
 
-    init() {
+    init(mode: SpeechRecognitionController.ListeningMode) {
+        print("**** Desired listening mode: \(mode)")
+        self.desiredListeningMode = mode
```
Comment (jsmorgan42) [inline Vocable/Features/Voice/AudioPermissionPromptController.swift:28]: I'm a little confused how this new property is used at all. Is this related to the variable being passed into through the EmptyState closure?

**Comment by CananArikan** [comment]
Test Verified!

Test Devices:
- iPad Pro - Test Device - iOS 15.3.1
- iPhone 11 - Simulator - iOS 15.4

Version: 
- 1.4.1-1

File: Vocable/Features/Voice/AudioPermissionPromptController.swift (hunk 1 above)
Comment (moyerr) [reply Vocable/Features/Voice/AudioPermissionPromptController.swift:61]: It's an instance property on this class. Rather than capturing self weakly and risking the loss of our desired listening mode (in the event that `self` is deallocated before this closure is executed), we can just capture the value directly.

Check out the [Swift Language Reference section on Capture Lists](https://docs.swift.org/swift-book/ReferenceManual/Expressions.html#ID544) if this isn't something you've seen before.

File: Vocable/Features/Voice/AudioPermissionPromptController.swift (hunk 2 above)
Comment (moyerr) [reply Vocable/Features/Voice/AudioPermissionPromptController.swift:28]: It tells the `SpeechRecognitionController` how we would like to start listening, once permissions have been granted. 

- When we initialize the `AudioPermissionPromptController` from Settings, we tell it that we want to listen in `hotWord` mode.
- When we initialize the `AudioPermissionPromptController` from the Listen category on the home screen, we tell it that we want to listen in `transcribing` mode.

File: Vocable/Features/Voice/AudioPermissionPromptController.swift (hunk 1 above)
Comment (jsmorgan42) [reply Vocable/Features/Voice/AudioPermissionPromptController.swift:61]: Ohhh ok, that makes a lot more sense

**Review by jsmorgan42 — APPROVED** [review]
🙌
