### PR TITLE
Fix Keyboard Screen Tests

### LINKED ISSUE #466: Fix KeyboardScreenTests
KeyboardScreenTests need to be fixed.

This issue is a sub-task of #405

### PR DESCRIPTION
**Pull request by CananArikan**
closes #466 
The parent issue to https://github.com/willowtreeapps/vocable-ios/issues/466 is https://github.com/willowtreeapps/vocable-ios/issues/405

# Description of Work
Fixed broken keyboard tests. This is part of the effort to unlink the chained tests.

### CODE REVIEW

File: VocableUITests/Tests/KeyboardScreenTests.swift [hunk 1]
```diff
@@ -3,30 +3,59 @@
...
+        keyboardScreen.typeText(testPhrase)
+        keyboardScreen.favoriteButton.tap()
+        keyboardScreen.dismissKeyboardButton.tap()
+        mainScreen.scrollToMySayings()
+         
+        XCTAssertFalse(mainScreen.isTextDisplayed(testPhrase), "Expected the phrase \(testPhrase) to be deleted from 'My Sayings'")
+    }
+    
+
+
```
Comment (Clstroud) [inline VocableUITests/Tests/KeyboardScreenTests.swift]:
```suggestion
```

File: VocableUITests/Screens/MainScreen.swift [hunk 2]
```diff
@@ -51,4 +51,39 @@ class MainScreen: BaseScreen {
...
+        
+        // Loop through each custom category page to find our phrase
+        for _ in 1...totalPageCount {
+            if app.cells.staticTexts.containing(predicate).element.exists {
+                break
+            } else {
+                paginationRightButton.tap()
+            }
+        }
+    }
```
Comment (Clstroud) [inline VocableUITests/Screens/MainScreen.swift]: I like the structure y'all have come up with here! I've got one overarching suggestion we can discuss, but I want to emphasize that this is just me thinking aloud 😄
 
I think you might be able to find some harmony with the `XCUITest` framework by separating the notion of _locating_ a particular `XCUIElement` from _interacting_ with that element. Currently there is an inconsistency where one function specifies that it will find a category and also tap, but the other finds a phrase and doesn't really let the caller know if it was successful or not 🤭 

So in practice I might suggest something like (I'm making this up on the fly):
`func locateCategoryCell(matching identifier: String) -> XCUIElement?` and
`func locatePhraseCell(withText text: String) -> XCUIElement?`
You would be able to very cleanly add an assertion that your element exists (is non-nil) and then tap it like you would any other element.

You could even compose the two with a new function:
`func locatePhraseCell(withText text: String, inCategoryMatchingIdentifier categoryID: String) -> XCUIElement?`
in order to cut down on future boilerplate.

File: VocableUITests/Screens/MainScreen.swift [hunk 3]
```diff
@@ -51,4 +51,39 @@ class MainScreen: BaseScreen {
         let currentCategory = defaultCategories.count - (numTimesToScroll % defaultCategories.count)
         app.collectionViews.staticTexts[defaultCategories[currentCategory]].tap()
     }
+    
+    func scrollToMySayings() {
+        let mySayingsIdentifier = "category_title_cell_preset_user_favorites"
```
Comment (Clstroud) [inline VocableUITests/Screens/MainScreen.swift]: It may make sense to have an enum of Categories where these identifiers can be stored. Then you could refer to those identifiers when scrolling to a particular category instead of having to make individual functions for each 🤔

Comment (rhsalas3) [reply VocableUITests/Screens/MainScreen.swift]: That's something I've been thinking about as well, while we start adding more and more identifiers. And especially now that we know that categories already have unique IDs we can reference.

To further clarify your suggestion when it comes to this particular function, does that look something like `func scrollToCategory(category: Category)` thus a call to it would be `mainScreen.scrollToCategory(Category.MySayings)`?

File: VocableUITests/Tests/KeyboardScreenTests.swift [hunk 4]
```diff
@@ -3,30 +3,59 @@
...
         keyboardScreen.favoriteButton.tap()
         keyboardScreen.dismissKeyboardButton.tap()
-        mainScreen.scrollLeftAndTapCurrentCategory(numTimesToScroll: 1)
-
-        XCTAssert(mainScreen.isTextDisplayed(testPhrase), "Expected the phrase \(testPhrase) to be added to an displayed in 'My Sayings'")
+        
+        mainScreen.scrollToMySayings()
+        mainScreen.findPhrase(phrase: testPhrase)
+        
+        XCTAssertTrue(mainScreen.isTextDisplayed(testPhrase), "Expected the phrase \(testPhrase) to be added to an displayed in 'My Sayings'")
```
Comment (rowildcard) [inline VocableUITests/Tests/KeyboardScreenTests.swift]: Typo. I believe you wanted your error message to say, "... added to _and_ displayed..."

File: VocableUITests/Tests/KeyboardScreenTests.swift [hunk 5]
```diff
@@ -3,30 +3,59 @@
...
+       
+        mainScreen.keyboardNavButton.tap()
+        keyboardScreen.typeText(testPhrase)
+        keyboardScreen.favoriteButton.tap()
+        keyboardScreen.dismissKeyboardButton.tap()
+       
+        mainScreen.scrollToMySayings()
+        mainScreen.findPhrase(phrase: testPhrase)
+       
+        XCTAssertTrue(mainScreen.isTextDisplayed(testPhrase), "Expected the phrase \(testPhrase) to be added to an displayed in 'My Sayings'")
```
Comment (rowildcard) [inline VocableUITests/Tests/KeyboardScreenTests.swift]: Ditto.
Typo. I believe you wanted your error message to say, "... added to _and_ displayed..."

File: VocableUITests/Tests/KeyboardScreenTests.swift (hunk 1 above)
Comment (CananArikan) [reply VocableUITests/Tests/KeyboardScreenTests.swift]: Fixed.

File: VocableUITests/Screens/MainScreen.swift (hunk 2 above)
Comment (CananArikan) [reply VocableUITests/Screens/MainScreen.swift]: Functions are updated as suggested.

File: VocableUITests/Screens/MainScreen.swift (hunk 3 above)
Comment (CananArikan) [reply VocableUITests/Screens/MainScreen.swift]: Added CategoryIdentifier/CategoryTitleCellIdentifier structs so that we now have a type to be used for passing along the category title cell element identifiers.

File: VocableUITests/Tests/CategoryIdentifier.swift [hunk 6]
```diff
@@ -0,0 +1,48 @@
...
+
+struct CategoryTitleCellIdentifier {
+
+    private let categoryIdentifier: CategoryIdentifier
+    let categoryTitleCellPrefix: String = "category_title_cell_"
+    
+    // Empty: used to retrieve the prefix only
+    init() {
+        self.categoryIdentifier = CategoryIdentifier("")
+    }
```
Comment (Clstroud) [inline VocableUITests/Tests/CategoryIdentifier.swift]: I think you might be able to declare the prefix as `static let prefix: String = "category_title_cell_"`, which would mean you don't have to actually instantiate this struct to access it: `CategoryTitleCellIdentifier.prefix`

File: VocableUITests/Screens/MainScreen.swift [hunk 7]
```diff
@@ -25,6 +25,22 @@ class MainScreen: BaseScreen {
...
+        let isSelectedPredicate = NSPredicate(format: "isSelected == true")
+        
+        // Build our query that first finds all category title cells, then finds among those the one that is selected
+        let query = XCUIApplication().cells.containing(identifierPredicate).containing(isSelectedPredicate)
+        
+        // Remove the identifierPrefix
+        let categoryTitleCellIdentifierString = query.element.identifier.replacingOccurrences(of: identifierPrefix, with: "")
+          
+        // Return the selected category's full identifier
+        return CategoryTitleCellIdentifier(CategoryIdentifier(categoryTitleCellIdentifierString))
```
Comment (Clstroud) [inline VocableUITests/Screens/MainScreen.swift]: I think it might make sense to move this logic into `CategoryTitleCellIdentifier` itself, giving it a [failable initializer](https://www.hackingwithswift.com/sixty/10/9/failable-initializers) that takes a `String`, and attempts to locate and remove the prefix.

**Review by Clstroud — COMMENTED** [review]
I have just two small suggestions and then I think this will be 💯 Y'all are doing great

File: VocableUITests/Tests/CategoryIdentifier.swift (hunk 6 above)
Comment (CananArikan) [reply VocableUITests/Tests/CategoryIdentifier.swift]: Fixed.

File: VocableUITests/Screens/MainScreen.swift (hunk 7 above)
Comment (CananArikan) [reply VocableUITests/Screens/MainScreen.swift]: Updated as suggested.

**Review by Clstroud — APPROVED** [review]
Nicely done! 🚢 💯

**Review by rowildcard — APPROVED** [review]

File: VocableUITests/Tests/KeyboardScreenTests.swift (hunk 4 above)
Comment (CananArikan) [reply VocableUITests/Tests/KeyboardScreenTests.swift]: Fixed.

File: VocableUITests/Tests/KeyboardScreenTests.swift (hunk 5 above)
Comment (CananArikan) [reply VocableUITests/Tests/KeyboardScreenTests.swift]: Fixed.
