### PR TITLE
Fixes for My Sayings scrolling and deletion animations

### LINKED ISSUE #139: Animation bug when deleting my sayings cell
On the Edit My Sayings screen, if there is only one cell left on the next page & the user deletes the last cell on the first page, an animation bug occurs. See below.

ezgif com-video-to-gif

### PR DESCRIPTION
**Pull request by Clstroud**
Resolves #139 
* Fixes an issue where deleting the last item on a page would not scroll back to the previous page correctly
* Improves touch handling performance
* Prevents cell selection/highlight on My Sayings

### CODE REVIEW

File: Vocable/Common/CarouselGridCollectionViewController.swift [hunk 1]
```diff
@@ -174,13 +177,17 @@ class CarouselGridLayout: UICollectionViewLayout {
...
+            return
+        }
 
         // Handles the case of the last item being deleted from the visible page
         if logicalPageIndex >= numberOfPages {
-            let rect = boundsRectForPageIndex(-1)
-            collectionView.scrollRectToVisible(rect, animated: animateIfNeeded)
-            logicalPageIndex -= 1
+            // Snap to the rightmost page before animating smoothly back to center.
+            collectionView.scrollRectToVisible(boundsRectForPageIndex(2), animated: false)
```
Comment (jsmorgan42) [inline Vocable/Common/CarouselGridCollectionViewController.swift:188]: Why is this a hard-coded value of 2?

File: Vocable/Common/CarouselGridCollectionViewController.swift [hunk 2]
```diff
@@ -197,6 +204,18 @@ class CarouselGridLayout: UICollectionViewLayout {
         return true
     }
 
+    private func visiblePages(forBounds bounds: CGRect) -> Set<Int> {
+        var pages = Set<Int>([0])
+        let tx = bounds.origin.x.distance(to: resetRect.origin.x)
```
Comment (jsmorgan42) [inline Vocable/Common/CarouselGridCollectionViewController.swift:209]: What does the t represent in this variable name?

**Review by jsmorgan42 — APPROVED** [review]
LGTM, had a couple questions

File: Vocable/Common/CarouselGridCollectionViewController.swift (hunk 1 above)
Comment (Clstroud) [reply Vocable/Common/CarouselGridCollectionViewController.swift:188]: Because the there are 3 "physical" pages of the scrollview that we use to represent all potential logical pages. Indexed [0, 1, 2]. It constantly resets back to 1 so in this case we need to snap over to 2 and animate back to 1 to get the right effect.

File: Vocable/Common/CarouselGridCollectionViewController.swift (hunk 2 above)
Comment (Clstroud) [reply Vocable/Common/CarouselGridCollectionViewController.swift:209]: Translation. Just like the `.tx` and `.ty` instance properties of `CGAffineTransform`

**Review by stevefosterwta — APPROVED** [review]
👍
