### PR TITLE
Fixed Settings Screen Tests

### LINKED ISSUE #480: Fix SettingScreenTests
SettingScreenTests need to be fixed.

This issue is a sub-task of https://github.com/willowtreeapps/vocable-ios/issues/405

### PR DESCRIPTION
**Pull request by CananArikan**
testHideShowToggle is fixed, closes #480 
The parent issue to #480 is #405 

# Description of Work
Fixed broken settings screen test. This is part of the effort to unlink the chained tests.

### CODE REVIEW

File: VocableUITests/Tests/CustomCategoriesTests.swift [hunk 1]
```diff
@@ -13,6 +13,7 @@ class CustomCategoriesTests: CustomCategoriesBaseTest {
     func testAddNewPhrase() {
         let customPhrase = "dd"
         let confirmationAlert = "Are you sure? Going back before saving will clear any edits made."
```
Comment (Clstroud) [inline VocableUITests/Tests/CustomCategoriesTests.swift]: We should probably give this an identifier instead of keying off of the actual string, since this is subject to change and would break the test?

Comment (Clstroud) [reply VocableUITests/Tests/CustomCategoriesTests.swift]: Looks like that identifier is currently `text_editor.alert.cancel_editing_confirmation.title`

File: VocableUITests/Tests/SettingsScreenTests.swift [hunk 2]
```diff
@@ -3,45 +3,42 @@
...
+
+        // Verify that when the category is shown, up and down buttons are enabled.
+        settingsScreen.locateCategoryCell(category).buttons[settingsScreen.categoryForwardButton].tap()
+        settingsScreen.showCategorySwitch.tap()
+        settingsScreen.leaveCategoryDetailButton.tap()
+        
+        settingsScreen.locateCategoryCell(category)
+        XCTAssertTrue(settingsScreen.locateCategoryCell(category).buttons[settingsScreen.categoryUpButton].isEnabled)
+        XCTAssertTrue(settingsScreen.locateCategoryCell(category).buttons[settingsScreen.categoryDownButton].isEnabled)
+        XCTAssertTrue(settingsScreen.locateCategoryCell(category).buttons[settingsScreen.categoryForwardButton].isEnabled)
```
Comment (Clstroud) [inline VocableUITests/Tests/SettingsScreenTests.swift]:
```suggestion
        let categoryCell = settingsScreen.locateCategoryCell(category)
        guard categoryCell.waitForExistence(20) else 
            XCTFail("Couldn't locate category cell")
            return
        }        
        XCTAssertTrue(categoryCell.buttons[settingsScreen.categoryUpButton].isEnabled)
        XCTAssertTrue(categoryCell.buttons[settingsScreen.categoryDownButton].isEnabled)
        XCTAssertTrue(categoryCell.buttons[settingsScreen.categoryForwardButton].isEnabled)
```
Just using this one snippet as an example, I think you can grab the cell element once and store it as a variable to reference in the assertions below it. I also threw in a `waitForExistence` because I'm not sure exactly what happens if `locateCategoryCell()` is unsuccessful, but [there are other strategies](https://mokacoding.com/blog/write-better-swift-tests-with-xctest-assertions/) that might help with that. Not a huge deal, mostly just wanted to grab the cell once for performance and readability reasons 😄

File: VocableUITests/Screens/SettingsScreen.swift [hunk 3]
```diff
@@ -17,39 +18,51 @@ class SettingsScreen: BaseScreen {
...
                 break
             } else {
                 settingsPageNextButton.tap()
             }
         }
+        
+        return categoryCellQuery(category)
+    }
+    
+    func categoryCellQuery(_ category: String) -> XCUIElementQuery {
```
Comment (Clstroud) [inline VocableUITests/Screens/SettingsScreen.swift]: Does this get used outside this context? I wonder if maybe it can be `private`?

File: VocableUITests/Tests/SettingsScreenTests.swift [hunk 4]
```diff
@@ -54,18 +51,19 @@ class SettingsScreenTests: BaseTest {
         XCTAssert(settingsScreen.otherElements.containing(.staticText, identifier: generalCategoryText).element.exists)
         XCTAssert(settingsScreen.otherElements.containing(.staticText, identifier: basicNeedsCategoryText).element.exists)
```
Comment (Clstroud) [inline VocableUITests/Tests/SettingsScreenTests.swift:52]: Based on some of the test failures I've seen recently, we should probably be using `waitForExistence()` to handle slow transition animations. I'm worried this could potentially be flaky otherwise, but I might be missing some context.

Comment (Clstroud) [reply VocableUITests/Tests/SettingsScreenTests.swift:52]: Also: same note about storing elements as variables. `settingsScreen.otherElements.containing(.staticText, identifier: generalCategoryText).element` is _very_ long and difficult to read multiple times 😅

**Review by Clstroud — CHANGES_REQUESTED** [review]
Structurally this seems pretty solid, but I left some feedback notes for tightening things up a bit. Happy to discuss any/all suggestions 😄

File: VocableUITests/Tests/SettingsScreenTests.swift (hunk 4 above)
Comment (CananArikan) [reply VocableUITests/Tests/SettingsScreenTests.swift:52]: We disabled this test for now, the code you pointed out is something we plan to refactor but we are waiting for #492 to be completed because of the Categories UI changes. When that ticket is completed we plan to update the flow in this test.

File: VocableUITests/Screens/SettingsScreen.swift (hunk 3 above)
Comment (CananArikan) [reply VocableUITests/Screens/SettingsScreen.swift]: We were thinking that we would use it outside of this context when we fix some of the other tests. But right now it is just being used here. I think we will go ahead and make it private. We can always change it back when we need to 😉

File: VocableUITests/Tests/CustomCategoriesTests.swift (hunk 1 above)
Comment (Clstroud) [reply VocableUITests/Tests/CustomCategoriesTests.swift]: Just realized this ^ may not actually be the accessibility ID, so I might've accidentally lied there. It's definitely the localization key, and I'm thinking we may want to make them match up for elements like this.

File: VocableUITests/Tests/SettingsScreenTests.swift (hunk 2 above)
Comment (CananArikan) [reply VocableUITests/Tests/SettingsScreenTests.swift]: We try to “handle" what happens if the cell is not present initially in the loop within `locateCategoryCell()`. We don't throw a failure explicitly but we do let the query fail which will report that the cell could not be found. Before that, however, we scroll the pages within the list of categories to find the cell we're looking for. 

Making a reference to the cell once in order to shorten our run time and the line of code is a good idea. We will implement that.

File: VocableUITests/Tests/CustomCategoriesTests.swift (hunk 1 above)
Comment (CananArikan) [reply VocableUITests/Tests/CustomCategoriesTests.swift]: Fixed!

File: VocableUITests/Tests/SettingsScreenTests.swift (hunk 2 above)
Comment (CananArikan) [reply VocableUITests/Tests/SettingsScreenTests.swift]: Fixed.

File: VocableUITests/Screens/SettingsScreen.swift (hunk 3 above)
Comment (CananArikan) [reply VocableUITests/Screens/SettingsScreen.swift]: We updated it!

**Review by Clstroud — APPROVED** [review]
🏆 💯 🥇 Nice updates!
