### PR TITLE
[647] Bug Fix for Listening Mode Settings Screen

### LINKED ISSUE #647: Listening Mode's settings' description text cut off on iPhone devices
### Description:
On iPhones with smaller screen sizes (height wise) or when rotating the device to landscape, the description text for the Listening Mode's settings is cut off at the bottom. The screen is not scrollable, so you cannot read the rest of the text.

**Steps:**
One a smaller iPhone, or while any iPhone is in landscape:
1. Navigate to Settings > Listening Mode
2. Note the description text under the Hey Vocable shortcut setting

**Expected behavior:**
All of the description text should be visible; either by scrolling or the text resizing dynamically.

**Actual behavior:**
The description text is cut off. Since the screen is not scrollable there is no way to read it.

### Screenshots:
1 ListeningMode_settingsScreen_doesNotAdjust_toDeviceDimensions

2 ListeningMode_settingsScreen_doesNotAdjust_toDeviceDimensions_landscape

**Device Information:**
 - Device: Any; but specifically iPhone 8 Plus is cut off in portrait; any iPhone will be cut off in landscape
 - OS: any

### PR DESCRIPTION
**Pull request by jsmorgan42**
closes #647

# Description of Work
Adjusted font & spacing on iPhone so that the footer is no longer cut off. Also enables scrolling in the listen mode settings screen so that the user can scroll down to the footer in landscape on iPhone if it still gets cut off in the future.

| Orientation | iPhone Mini | iPad Mini |
| :--- | :---: | :---: |
| Portrait |  |  |
| Landscape |  |  |

---

### CODE REVIEW

**Comment by rhsalas3** [comment]
This fix looks good! 💸  💸

File: Vocable/Features/Settings/ListeningMode/ListeningModeViewController.swift [hunk 1]
```diff
@@ -150,12 +149,13 @@ final class ListeningModeViewController: VocableCollectionViewController {
...
                 text = String(localized: "settings.listening_mode.hotword_explanation_footer")
             }
+            footerView.textLabel.font = self.sizeClass.contains(any: .compact) ? .systemFont(ofSize: 18) : .systemFont(ofSize: 26)
             footerView.textLabel.text = text
             return footerView
         }
 
         let configuration = UICollectionViewCompositionalLayoutConfiguration()
-        configuration.interSectionSpacing = 44
+        configuration.interSectionSpacing = 16
```
Comment (moyerr) [inline Vocable/Features/Settings/ListeningMode/ListeningModeViewController.swift]: Do we also want to make this based on whether we're in a compact size class?

File: Vocable/Features/Settings/ListeningMode/ListeningModeViewController.swift [hunk 2]
```diff
@@ -150,12 +149,13 @@ final class ListeningModeViewController: VocableCollectionViewController {
             case .hotword:
                 text = String(localized: "settings.listening_mode.hotword_explanation_footer")
             }
+            footerView.textLabel.font = self.sizeClass.contains(any: .compact) ? .systemFont(ofSize: 18) : .systemFont(ofSize: 26)
```
Comment (Clstroud) [inline Vocable/Features/Settings/ListeningMode/ListeningModeViewController.swift]:
```suggestion
            let fontSize = sizeClass.contains(any: .compact) ? 18 : 26
            footerView.textLabel.font = .systemFont(ofSize: fontSize)
```

**Review by Clstroud — APPROVED** [review]
Good stuff! Only one suggestion 🏆

File: Vocable/Features/Settings/ListeningMode/ListeningModeViewController.swift (hunk 1 above)
Comment (jsmorgan42) [reply Vocable/Features/Settings/ListeningMode/ListeningModeViewController.swift]: Not a bad idea, I'll add that in

**Review by moyerr — APPROVED** [review]
